# This workflow is a reusable one called by other workflows
name: Latest Standalone UI installation

on:
  workflow_dispatch:

jobs:
  E2E-Cypress:
    runs-on: ui-e2e-3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Epinio repository
        uses: actions/checkout@v2
        with:
          repository: epinio/epinio
          submodules: recursive
          fetch-depth: 0
          path: epinio

      - name: Checkout Rancher Dashboard repository
        uses: actions/checkout@v2
        with:
          repository: rancher/dashboard
          ref: epinio-dev
          path: dashboard

      - name: Checkout Epinio UI-backend repository
        uses: actions/checkout@v2
        with:
          repository: epinio/ui-backend 
          path: ui-backend 

      - name: Setup Go
        uses: actions/setup-go@v2
        env:
          SETUP_GO_VERSION: '^1.18.0'
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.2.0

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools

      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH

      - name: Install K3s / Helm / Epinio
        id: installation
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          HELM_VERSION: 3.7.0
          K3S_VERSION: v1.22.7+k3s1
          EXT_REG: ${{ inputs.ext_reg }}
          EXT_REG_USER: ${{ secrets.DOCKER_USER }}
          EXT_REG_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          S3_KEY_ID: ${{ secrets.s3_key_id }}
          S3_KEY_SECRET: ${{ secrets.s3_key_secret }}
        run: |
          ## Export information
          ETH_DEV=$(ip route | awk '/default via / { print $5 }')
          MY_IP=$(ip a s ${ETH_DEV} | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
          export MY_HOSTNAME=$(hostname)
          export EPINIO_SYSTEM_DOMAIN="${MY_IP}.omg.howdoi.website"
          echo '::set-output name=EPINIO_SYSTEM_DOMAIN::'${EPINIO_SYSTEM_DOMAIN}
          make prepare-e2e-ci-standalone

      - name: Deploy latest dev standalone UI
        env:
          EPINIO_SYSTEM_DOMAIN: ${{ steps.installation.outputs.EPINIO_SYSTEM_DOMAIN }}
        run: |
          make deploy-latest-dev-std-ui
      
      - name: Start Cypress tests
        env:
          BROWSER: chrome
          CORS: https://${{ needs.installation.outputs.MY_HOSTNAME }}
          CYPRESS_CFG: cypress-with-epinio-cert.json
          CYPRESS_DOCKER: cypress/included:9.7.0 
          EXT_REG_USER: ${{ secrets.DOCKER_USER }}
          EXT_REG_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          RANCHER_PASSWORD: password
          RANCHER_URL: https://host.docker.internal:8005
          RANCHER_USER: admin
          SPEC: cypress/integration/scenarios/with_default_options.spec.ts
        run: |
          sleep 240
          ETH_DEV=$(ip route | awk '/default via / { print $5 }')
          MY_IP=$(ip a s ${ETH_DEV} | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
          export EPINIO_SYSTEM_DOMAIN="${MY_IP}.omg.howdoi.website"
          make start-cypress-tests

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

      - name: Uninstall Epinio
        if: always()
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          make uninstall-epinio

      - name: Delete k3s cluster
        if: always()
        run: |
          make clean-k3s

      - name: Clean all
        if: always()
        uses: colpal/actions-clean@v1
