# This workflow calls the master UI workflow with custom variables
name: Rancher-UI-2-Firefox

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 2 * * *'

jobs:
  rancher-firefox:
    uses: ./.github/workflows/master_rancher_ui_workflow.yml
    with:
      browser: firefox
      cypress_image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      cypress_install_test: installation.spec.ts
      # cypress_test: with_s3_and_external_registry.spec.ts
      cypress_test: menu.spec.ts
      # Due to security reason, Firefox can't be started as root
      # https://github.com/cypress-io/github-action#firefox
      docker_options: '--user 1000'
      runner: ui-e2e
      # ext_reg: '1'
    secrets: inherit
