# This workflow calls the master UI workflow with custom variables
name: Rancher-UI-1-Chrome

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

jobs:
  rancher-chrome:
    uses: ./.github/workflows/master_rancher_ui_workflow.yml
    with:
      browser: chrome
      cypress_image: cypress/included:cypress-12.12.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
      cypress_install_test: installation.spec.ts
      # cypress_test: with_default_options.spec.ts
      cypress_test: menu.spec.ts
      runner: ui-e2e-0
    secrets: inherit
