# This workflow calls the master UI workflow with custom variables
name: Rancher-UI-1-Chrome

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 2 * * *'

jobs:
  rancher-chrome:
    uses: ./.github/workflows/master_rancher_ui_workflow.yml
    with:
      browser: chrome
      cypress_image: cypress/browsers:node16.13.2-chrome97-ff96
      cypress_install_test: installation.spec.ts
      cypress_test: with_default_options.spec.ts
      runner: ui-e2e-0
    secrets:
      ext_reg_user: secrets.EPINIO_DOCKER_USER
      ext_reg_password: secrets.EPINIO_DOCKER_PASSWORD
