# This workflow calls the master UI workflow with custom variables
# It will test deploying an application with s3 and ext registry configured
name: STD-UI-Latest-Firefox

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 2 * * *'

jobs:
# I keep the following tests commented out in case someone want to enable them later.
# Those are the same tests we are running on chrome, main differences are:
# - Firefox browser
# - Epinio installed with s3 and external registry
# They were working but with too much flakyness.

#  menu-tests:
    #uses: ./.github/workflows/master_std_ui.yml
    #with:
      #browser: firefox
      #cypress_docker: cypress/included:10.9.0
      #cypress_spec: cypress/e2e/unit_tests/menu.spec.ts
      #docker_options: '--user 1000'
      #ext_reg: '1'
      #s3: '1'
    #secrets: inherit

  #configurations-tests:
    #uses: ./.github/workflows/master_std_ui.yml
    #with:
      #browser: firefox
      #cypress_docker: cypress/included:10.9.0
      #cypress_spec: cypress/e2e/unit_tests/configurations.spec.ts
      #docker_options: '--user 1000'
      #ext_reg: '1'
      #s3: '1'
    #secrets: inherit

  #applications-tests:
    #uses: ./.github/workflows/master_std_ui.yml
    #with:
      #browser: firefox
      #cypress_docker: cypress/included:10.9.0
      #cypress_spec: cypress/e2e/unit_tests/applications.spec.ts
      #docker_options: '--user 1000'
      #ext_reg: '1'
      #s3: '1'
    #secrets: inherit

  commandCall-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: firefox
      cypress_docker: cypress/included:10.9.0
      cypress_spec: cypress/e2e/unit_tests/commandCall-example.spec.ts
      docker_options: '--user 1000'
      ext_reg: '1'
      s3: '1'
    secrets: inherit

  namespaces-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: firefox
      cypress_docker: cypress/included:10.9.0
      cypress_spec: cypress/e2e/unit_tests/namespaces.spec.ts
      docker_options: '--user 1000'
      ext_reg: '1'
      s3: '1'
    secrets: inherit