# This workflow calls the master UI workflow with custom variables
# It will test all Epinio parts
name: STD-UI-Latest-Chrome

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 4 * * *'

# I do not know if I can refactor with a matrix in a reusable workflow?
jobs:
## Adding checks to the runner
  check-runner:
    runs-on: self-hosted
    steps:
      - run: df -h
      - run: ps auxf
      - run: sudo dmesg
      - run: docker ps
      - run: docker images
      - run: sudo ss -tupan
      
  menu-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: chrome
      cypress_docker: cypress/included:10.11.0 
      cypress_spec: cypress/e2e/unit_tests/menu.spec.ts
    secrets: inherit

  configurations-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: chrome
      cypress_docker: cypress/included:10.11.0 
      cypress_spec: cypress/e2e/unit_tests/configurations.spec.ts
    secrets: inherit

  applications-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: chrome
      cypress_docker: cypress/included:10.11.0 
      cypress_spec: cypress/e2e/unit_tests/applications.spec.ts
    secrets: inherit

  namespaces-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: chrome
      cypress_docker: cypress/included:10.11.0 
      cypress_spec: cypress/e2e/unit_tests/namespaces.spec.ts
    secrets: inherit
