# This workflow calls the master UI workflow with custom variables
# It will test deploying an application with s3 and ext registry configured
name: STD-UI-Latest-Firefox

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 2 * * *'

jobs:
  std-firefox:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: firefox
      cypress_docker: cypress/included:9.7.0
      cypress_spec: cypress/integration/scenarios/with_s3_and_external_registry.spec.ts
      # Due to security reason, Firefox can't be started as root
      # https://github.com/cypress-io/github-action#firefox
      docker_options: '--user 1000'
      ext_reg: '1'
    secrets:
      ext_reg_user: secrets.EPINIO_DOCKER_USER
      ext_reg_password: secrets.EPINIO_DOCKER_PASSWORD
      s3_key_id: secrets.AWS_ACCESS_KEY_ID
      s3_key_secret: secrets.AWS_SECRET_ACCESS_KEY
