name: UI-CI

on:
  workflow_dispatch:

jobs:
  installation:
    runs-on: ui-e2e-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install K3s - Helm - Rancher
        id: installation
        env:
          DASHBOARD_VERSION: epinio-v0.3.3
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          HELM_VERSION: 3.7.0
        run: |
          export MY_HOSTNAME=$(hostnamectl hostname)
          make e2e-ci

          ## Export information to other jobs
          ETH_DEV=$(ip route | awk '/default via / { print $5 }')
          echo '::set-output name=MY_IP::'$(ip a s ${ETH_DEV} | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
          echo '::set-output name=MY_HOSTNAME::'$(hostnamectl hostname)
    outputs:
      MY_HOSTNAME: ${{ steps.installation.outputs.MY_HOSTNAME}}
      MY_IP: ${{ steps.installation.outputs.MY_IP}}
 
  cypress-run:
    needs:
      - installation
    runs-on: ui-e2e-1
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      env:
        RANCHER_USER: admin
        RANCHER_PASSWORD: rancherpassword
        RANCHER_URL: https://${{ needs.installation.outputs.MY_HOSTNAME }}/dashboard
        CLUSTER_NAME: local
        SYSTEM_DOMAIN: ${{ needs.installation.outputs.MY_IP }}.omg.howdoi.website
        CORS: https://${{ needs.installation.outputs.MY_HOSTNAME }}
      options: --add-host ${{ needs.installation.outputs.MY_HOSTNAME}}:${{ needs.installation.outputs.MY_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Specify Browser since container image is compile with Firefox
          browser: chrome
          spec: |
            cypress/integration/unit_tests/first_connexion.spec.ts
            cypress/integration/unit_tests/installation.spec.ts
            cypress/integration/unit_tests/menu.spec.ts

  delete-cluster:
    if: always()
    needs: [installation, cypress-run]
    runs-on: ui-e2e-1
    steps:
      - name: Delete k3s cluster
        run: |
          sudo /usr/local/bin/k3s-uninstall.sh
          helm repo remove rancher-stable jetstack

